# Generated by Django 5.1.4 on 2024-12-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True, verbose_name="last login"),
        ),
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default=2222, max_length=128, verbose_name="password"),
            preserve_default=False,
        ),
    ]
